### ISSUE TITLE
setFormatter is not working

### ISSUE THREAD

**Issue by bgyooPtr** [TrayserCassa/DiscordHandler#10]
I want to apply the logging formatter.
But now DiscordHandler does not support that function.

**Comment by Whisperes** [comment]
Yes, you should change code. I did it in my side. Maybe it will help you.
[https://github.com/Whisperes/pytils/blob/main/pytils/logger.py](https://github.com/Whisperes/pytils/blob/main/pytils/logger.py)

**Comment by TrayserCassa** [comment]
If you check the example you see that this is working. Check the `test_handler.py` in the example folder.
