### ISSUE TITLE
Publish to PyPi!

### ISSUE THREAD

**Issue by quanta-kt** [TrayserCassa/DiscordHandler#3]
Hi there! First off, thanks for the module. It saved me a good amount of time in a recent Django project where I had an idea in mind to push critical error to Discord and found your repository.

I'd love to see this code being published to PyPi for easy installation through pip. Do you want me to submit a PR with code cleanup and meeting requirements (setup.py, and moving the DiscordHandler class to a separate module, etc) for a PyPi submission?

**Comment by TrayserCassa** [comment]
Well sorry for the delayed answer. First time I get this kind of response for my `Projects`. Well you can do it if you want, but i can also push this tomorrow by myself :)
I hope this code is clean, if you find something that is wrong you can post it here, then I will fix it.

**Comment by TrayserCassa** [comment]
@quanta-kt 
Finished, have I done everything right? Maybe write better test with asset, but if the logging failed, then I get only console output.

**Comment by quanta-kt** [comment]
I noticed that you have your webhook URL in one of the examples, is that fine?
I think you are better off with a placeholder like `"your webhook url here"`.
I think the file under `tests/` can be moved to `examples/` (the name makes it confusing as directories with name `tests/` are often used for unit tests)

**Comment by TrayserCassa** [comment]
finished :) 
I executed the tests with pytest, but they will never fail. First time for me using tests in python. Well I moved it to examples.
